[package]
name = "vector-intersection-experiments"
version = "0.1.0"
authors = ["dissi <moreiras@informatik.uni-freiburg.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
array_tool = "1.0.3"